apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-personalization-api
  description: Manages user specific preferences within Workspace
spec:
  type: service
  lifecycle: production
  owner: guest